categories = ["Průměrná denní teplota vzduchu", 
         "Maximální denní teplota vzduchu", 
         "Minimální denní teplota vzduchu", 
         "Průměrná denní relativní vlhkost vzduchu", 
         "Denní úhrn srážek", 
         "Výška nově napadlého sněhu", 
         "Celková výška sněhové pokrývky", 
         "Denní úhrn doby trvání slunečního svitu", 
         "Průměrný denní tlak vzduchu", 
         "Průměrná denní rychlost větru", 
         "Maximální rychlost větru", 
         "Globální záření"]

regions = ["Hlavní město Praha", 
           "Středočeský kraj", 
           "Jihočeský kraj", 
           "Plzeňský kraj", 
           "Karlovarský kraj", 
           "Ústecký kraj", 
           "Liberecký kraj", 
           "Královéhradecký kraj", 
           "Pardubický kraj", 
           "Kraj Vysočina", 
           "Jihomoravský kraj", 
           "Olomoucký kraj", 
           "Moravskoslezský kraj", 
           "Zlínský kraj"]